version: 2.1

orbs:
  automation: willian-gama/android-ci@1.0.68

workflows:
  build_and_test:
    jobs:
      - automation/android_setup
      - automation/android_unit_tests:
          build_variant: debug
          parallelism: 2
          requires:
            - automation/android_setup
      - automation/android_screenshot_tests:
          build_variant: debug
          requires:
            - automation/android_setup
      - automation/android_ui_tests:
          build_variant: debug
          parallelism: 2
          requires:
            - automation/android_setup
      - automation/android_code_linting:
          build_variant: debug
          requires:
            - automation/android_setup
      - automation/android_code_coverage:
          requires:
            - automation/android_unit_tests
            - automation/android_ui_tests
